import type { ArchetypeDefinition } from "@/types/archetype";

export const ARCHETYPES: readonly ArchetypeDefinition[] = [
  {
    id: "attack",
    name: "Aggressor",
    deckName: "Aggressor Deck",
    quote: "Strike first. No mercy.",
    summary: "Attack-focused. Pure pressure.",
    primaryDimensions: ["attack"],
    vector: { attack: 1, defence: 0, control: 0 },
  },
  {
    id: "defence",
    name: "Fortress Mind",
    deckName: "Offense Deck",
    quote: "Protected power. Controlled aggression.",
    summary: "Fortified attack stance.",
    primaryDimensions: ["defence"],
    vector: { attack: 0, defence: 1, control: 0 },
  },
  {
    id: "control",
    name: "Silent Strategist",
    deckName: "Controlled Deck",
    quote: "Calm mastery. Outlast. Master the crease.",
    summary: "Patience until the crease is yours.",
    primaryDimensions: ["control"],
    vector: { attack: 0, defence: 0, control: 1 },
  },
  {
    id: "attack_control",
    name: "Conqueror / Strategist",
    deckName: "Caesar's Hand",
    quote: "I came, I saw, I flipped the table.",
    summary: "Pressure with a plan.",
    primaryDimensions: ["attack", "control"],
    vector: { attack: 0.5, defence: 0, control: 0.5 },
  },
  {
    id: "attack_defence",
    name: "Warfront Hybrid",
    deckName: "Legion Command",
    quote: "Charge, then hold the line.",
    summary: "Strike and survive the crease.",
    primaryDimensions: ["attack", "defence"],
    vector: { attack: 0.5, defence: 0.5, control: 0 },
  },
  {
    id: "defence_control",
    name: "Crease Master",
    deckName: "Silent Shield",
    quote: "Wait for the smoke. Then own the street.",
    summary: "Defence grown through patience.",
    primaryDimensions: ["defence", "control"],
    vector: { attack: 0, defence: 0.5, control: 0.5 },
  },
  {
    id: "balanced",
    name: "Estate Balanced",
    deckName: "Blood Seat",
    quote: "Own it. Control it. Live it.",
    summary: "All three directions live in the holster.",
    primaryDimensions: ["attack", "defence", "control"],
    vector: { attack: 1 / 3, defence: 1 / 3, control: 1 / 3 },
  },
];
