// Flip Three catalog data.
//
// Every entry is authored to work simultaneously as (1) a catalogue product,
// (2) a collectible card, (3) a future Flip Three game asset and (4) a piece of
// the wider DCBD universe. Attack / Defense are hand-balanced from each
// product's character (bright/bold profiles lean offensive; reserve/cream/ice
// profiles lean defensive) rather than randomly assigned. The Special Ability
// is intentionally concealed until the Flip Three game layer unlocks it.

export const TIERS = {
  common: { label: 'COMMON', grade: 'C', accent: '#a3a3a3', ring: 'border-zinc-500/40' },
  uncommon: { label: 'UNCOMMON', grade: 'B', accent: '#84cc16', ring: 'border-lime-400/40' },
  rare: { label: 'RARE CARD', grade: 'A', accent: '#38bdf8', ring: 'border-sky-400/40' },
  epic: { label: 'EPIC DROP', grade: 'AA', accent: '#a855f7', ring: 'border-purple-400/40' },
  legendary: { label: 'LEGENDARY', grade: 'AAA', accent: '#f59e0b', ring: 'border-amber-400/50' },
};

export const CATALOG = [
  {
    id: 'p038', no: 1, name: 'Pacific OG', category: 'Collector Range', tier: 'legendary',
    description: 'Pine-and-ocean-cliff collector artwork engineered as a defensive anchor for any three-card wall.',
    flavour: 'Pine resin, sea salt air and a cool lemon edge.',
    characteristics: ['Cliffside pine', 'Coastal cool', 'Anchor-grade'],
    attack: 71, defense: 94,
    ability: { name: 'Tidewall', hint: 'Turns the ▓▓▓▓ round into unbroken defence.' },
    art: { colorA: '#38bdf8', colorB: '#0c4a6e', motif: 'wave' },
  },
  {
    id: 'p037', no: 2, name: 'Cali Gold', category: 'Collector Range', tier: 'legendary',
    description: 'Golden-styled reserve card built to strike first and hardest in the opening exchange.',
    flavour: 'Earthy pine, warm lemon and golden citrus.',
    characteristics: ['Golden reserve', 'First-strike', 'Sun-cured'],
    attack: 90, defense: 66,
    ability: { name: 'Goldrush', hint: 'Banks ▓▓ extra pressure while ahead.' },
    art: { colorA: '#f1be48', colorB: '#78350f', motif: 'orbs' },
  },
  {
    id: 'p039', no: 3, name: 'Golden State', category: 'Collector Range', tier: 'legendary',
    description: 'Mango, pineapple and golden-coast artwork tuned for relentless offensive tempo.',
    flavour: 'Mango, pineapple and bright golden coast.',
    characteristics: ['Tropic bright', 'High tempo', 'Coast-forged'],
    attack: 93, defense: 61,
    ability: { name: 'Sunbreak', hint: 'Cracks a defender once per ▓▓▓▓▓▓.' },
    art: { colorA: '#f97316', colorB: '#431407', motif: 'poster' },
  },
  {
    id: 'p040', no: 4, name: 'Lost Coast Haze', category: 'Collector Range', tier: 'legendary',
    description: 'Top-shelf misty-coast profile — a balanced heavyweight that bends the game state.',
    flavour: 'Lemon, garden herbs and cool coastal mist.',
    characteristics: ['Misty haze', 'Balanced heavy', 'Reserve-grade'],
    attack: 88, defense: 74,
    ability: { name: 'Mistveil', hint: 'Hides your true ▓▓▓▓▓ from the AI read.' },
    art: { colorA: '#14b8a6', colorB: '#052e2b', motif: 'mist' },
  },
  {
    id: 'p044', no: 5, name: 'Pineapple Diesel', category: 'Collector Range', tier: 'epic',
    description: 'Bold collector artwork built as a glass-cannon: overwhelming attack, thin guard.',
    flavour: 'Pineapple, citrus and sharp diesel bite.',
    characteristics: ['Diesel bite', 'Glass cannon', 'Overdrive'],
    attack: 95, defense: 52,
    ability: { name: 'Overclock', hint: 'Spends defence to double a ▓▓▓▓ hit.' },
    art: { colorA: '#facc15', colorB: '#3f2d02', motif: 'orbs' },
  },
  {
    id: 'p045', no: 6, name: 'Mango Kush Diamonds', category: 'Collector Range', tier: 'legendary',
    description: 'Premium diamond-cut mango artwork — an even, all-rounder centrepiece.',
    flavour: 'Ripe mango, cream and crystalline sweetness.',
    characteristics: ['Diamond-cut', 'All-rounder', 'Premium'],
    attack: 84, defense: 80,
    ability: { name: 'Facet', hint: 'Reflects a portion of ▓▓▓▓▓▓ damage back.' },
    art: { colorA: '#fb923c', colorB: '#3b0764', motif: 'crystal' },
  },
  {
    id: 'p047', no: 7, name: 'Dragonfruit Resin', category: 'Collector Range', tier: 'epic',
    description: 'Sticky resin-berry artwork designed to lock opponents down and grind rounds out.',
    flavour: 'Dragonfruit, dark berry and sticky resin.',
    characteristics: ['Sticky resin', 'Lockdown', 'Control'],
    attack: 69, defense: 90,
    ability: { name: 'Bloomlock', hint: 'Freezes an enemy ▓▓▓▓▓▓▓ for one round.' },
    art: { colorA: '#ec4899', colorB: '#500724', motif: 'orbs' },
  },
  {
    id: 'p046', no: 8, name: 'Blueberry Melt', category: 'Collector Range', tier: 'epic',
    description: 'Smooth blueberry-melt artwork — a cool, forgiving defensive pick.',
    flavour: 'Blueberry, sugar and slow smooth melt.',
    characteristics: ['Cool melt', 'Forgiving', 'Frost guard'],
    attack: 63, defense: 88,
    ability: { name: 'Deepfreeze', hint: 'Slows the opponent ▓▓▓▓▓ queue.' },
    art: { colorA: '#3b82f6', colorB: '#0b1e3f', motif: 'wave' },
  },
  {
    id: 'p036', no: 9, name: 'Sunset Sherbet', category: 'Collector Range', tier: 'rare',
    description: 'Coastal sunset artwork with a perfectly even offence-and-guard split.',
    flavour: 'Sweet berry, citrus and coastal sunset.',
    characteristics: ['Sunset sweet', 'Even split', 'Flex pick'],
    attack: 77, defense: 78,
    ability: { name: 'Afterglow', hint: 'Restores guard when you ▓▓▓ a round.' },
    art: { colorA: '#fb7185', colorB: '#4a044e', motif: 'poster' },
  },
  {
    id: 'p042', no: 10, name: 'Coastal Dream', category: 'Collector Range', tier: 'epic',
    description: 'Lavender-and-berry coastline artwork — a fortress that survives the long game.',
    flavour: 'Lavender, sweet berry and salt breeze.',
    characteristics: ['Fortress', 'Late-game', 'Calm'],
    attack: 58, defense: 92,
    ability: { name: 'Lullwake', hint: 'Softens every incoming ▓▓▓▓▓▓.' },
    art: { colorA: '#a78bfa', colorB: '#1e1b4b', motif: 'mist' },
  },
  {
    id: 'p023', no: 11, name: 'Temple Ball Reserve', category: 'Classic Tea', tier: 'legendary',
    description: 'Reserve-style relic artwork — the near-immovable defensive legend of the set.',
    flavour: 'Sandalwood, black pepper and aged spice.',
    characteristics: ['Relic reserve', 'Near-immovable', 'Aged'],
    attack: 66, defense: 96,
    ability: { name: 'Relic Seal', hint: 'One round it simply ▓▓▓▓▓▓ be broken.' },
    art: { colorA: '#a16207', colorB: '#050505', motif: 'ball' },
  },
  {
    id: 'p027', no: 12, name: 'Afghan Cream', category: 'Classic Tea', tier: 'rare',
    description: 'Dark-chocolate heritage artwork with a deep, creamy defensive base.',
    flavour: 'Dark chocolate, earth and heavy cream.',
    characteristics: ['Heritage', 'Creamy base', 'Grounded'],
    attack: 60, defense: 89,
    ability: { name: 'Old Earth', hint: 'Roots your card against ▓▓▓▓▓▓ effects.' },
    art: { colorA: '#7f5539', colorB: '#1c1006', motif: 'ball' },
  },
  {
    id: 'p030', no: 13, name: 'Wedding Z Reserve', category: 'Classic Tea', tier: 'epic',
    description: 'Founder-drop dessert reserve — a poised, ceremonial two-way threat.',
    flavour: 'Sweet dessert, vanilla and smooth depth.',
    characteristics: ['Founder drop', 'Ceremonial', 'Two-way'],
    attack: 72, defense: 84,
    ability: { name: 'Vow', hint: 'Bonds two cards to share ▓▓▓▓▓▓▓.' },
    art: { colorA: '#f9a8d4', colorB: '#500724', motif: 'poster' },
  },
  {
    id: 'p031', no: 14, name: 'Patella 69', category: 'Classic Tea', tier: 'rare',
    description: 'Apple-gas collector blend built to punch above its grade on offence.',
    flavour: 'Green apple, gas and sharp collector edge.',
    characteristics: ['Apple gas', 'Overreach', 'Aggressive'],
    attack: 86, defense: 63,
    ability: { name: 'Fault Line', hint: 'Splits an enemy guard along a ▓▓▓▓▓.' },
    art: { colorA: '#16a34a', colorB: '#052e16', motif: 'crystal' },
  },
  {
    id: 'p032', no: 15, name: 'Jungle Boyz Reserve', category: 'Classic Tea', tier: 'rare',
    description: 'Graffiti-jungle artwork tuned for fast, tropical aggression.',
    flavour: 'Bold tropical fruit and wild green notes.',
    characteristics: ['Graffiti wild', 'Fast strike', 'Tropical'],
    attack: 89, defense: 58,
    ability: { name: 'Ambush', hint: 'Strikes before the ▓▓▓▓▓ resolves.' },
    art: { colorA: '#22c55e', colorB: '#052e16', motif: 'canopy' },
  },
  {
    id: 'p001', no: 16, name: 'Mango Kush', category: 'Herbal Tea', tier: 'uncommon',
    description: 'Sweet tropical entry card — friendly stats and a lively offensive lean.',
    flavour: 'Sweet mango, citrus and smooth tropics.',
    characteristics: ['Tropical', 'Beginner-friendly', 'Lively'],
    attack: 74, defense: 62,
    ability: { name: 'Sweet Static', hint: 'A tiny ▓▓▓▓ jolt each opening turn.' },
    art: { colorA: '#ff9f1c', colorB: '#3f1d02', motif: 'orbs' },
  },
  {
    id: 'p004', no: 17, name: 'Purple Haze', category: 'Herbal Tea', tier: 'rare',
    description: 'Iconic grape-and-floral haze — an ability-first wildcard.',
    flavour: 'Grape, berry and soft floral haze.',
    characteristics: ['Iconic haze', 'Wildcard', 'Ability-first'],
    attack: 80, defense: 70,
    ability: { name: 'Purple Fog', hint: 'Blurs the AI read of your ▓▓▓▓.' },
    art: { colorA: '#8e38ff', colorB: '#1e1b4b', motif: 'mist' },
  },
  {
    id: 'p006', no: 18, name: 'Berlin Berries', category: 'Herbal Tea', tier: 'uncommon',
    description: 'Dark city-night berry blend — a steady defensive support card.',
    flavour: 'Dark berry with a cool city-night profile.',
    characteristics: ['City-night', 'Steady', 'Support'],
    attack: 64, defense: 83,
    ability: { name: 'Nightshade', hint: 'Draws a sliver of enemy ▓▓▓▓▓▓ each round.' },
    art: { colorA: '#7c3aed', colorB: '#0b0221', motif: 'orbs' },
  },
  {
    id: 'p012', no: 19, name: 'Cherry Cola', category: 'Herbal Tea', tier: 'common',
    description: 'Fizzy cherry-cola starter — cheap, punchy and eager to attack.',
    flavour: 'Cherry cola with sweet fizzy bite.',
    characteristics: ['Fizzy', 'Punchy', 'Starter'],
    attack: 78, defense: 55,
    ability: { name: 'Fizzbomb', hint: 'Pops for burst ▓▓▓▓▓▓ then fades.' },
    art: { colorA: '#dc2626', colorB: '#3f0708', motif: 'poster' },
  },
  {
    id: 'p015', no: 20, name: 'Blue Raspberry Burst', category: 'Herbal Tea', tier: 'uncommon',
    description: 'Sweet-shop blue-raspberry burst — quick offensive pressure on a budget.',
    flavour: 'Blue raspberry sweet-shop rush.',
    characteristics: ['Sweet-shop', 'Quick pressure', 'Budget'],
    attack: 82, defense: 60,
    ability: { name: 'Burstline', hint: 'Chains a second hit on a ▓▓▓ streak.' },
    art: { colorA: '#38bdf8', colorB: '#082f49', motif: 'wave' },
  },
];
